// Unit tests: the timer's logic, physics and sounds, with no windows. Run with `./build.sh test`.
clockTests()
statsTests()
projectTests()
linkTests()
mcpTests()
updateTests()
sandTests()
motionTests()
tiltTests()
soundTests()
noiseTests()
themeTests()
TestKit.finish()
